SET IDENTITY_INSERT [dbo].[Countries] ON
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (6, N'Jamaica', N'JM')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (8, N'Test Country', N'TC')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (9, N'Test', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (10, N'Test', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (11, N'111', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (12, N'11', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (13, N'dubai', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (14, N'd1ubai', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (15, N'd2ubai', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (16, N'd7ubai', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (17, N'd8ubai', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (18, N'd77ubai', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (19, N'd7000ubai', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (20, N'ubai', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (21, N'ubai44', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (22, N'ubi44', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (23, N'u3333bi44', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (24, N'u33433bi44', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (25, N'u3534433bi44', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (26, N'u353443344', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (27, N'u35443344', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (28, N'u3443344', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (29, N'4oo5', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (30, N'noln', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (31, N'jbj', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (32, N'jb3j', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (33, N'mikel', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (34, N'mikel1', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (35, N'mikel0', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (36, N'mik99', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (37, N'mink99', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (38, N'm3ink99', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (39, N'3ink99', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (40, N'3in1k99', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (41, N'k99', N'd')
INSERT INTO [dbo].[Countries] ([CountryId], [Name], [ShortName]) VALUES (42, N'k989', N'd')
SET IDENTITY_INSERT [dbo].[Countries] OFF
