@HotelListing.Api_HostAddress = https://localhost:7238
@apikey=ac123
@json=application/json
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMWExMzFkOC0zMGM5LTQ5OWUtOGNhYS0xYWFjOWQ5NDA3NDUiLCJlbWFpbCI6IkFkbWluQWRtaW5AbG9jYWxob3N0LmNvbSIsImp0aSI6ImI2NDcwNzU3LWI0OGYtNDUwMi04NDI1LTlmNTdiY2YzMDRhZiIsIm5hbWUiOiJhZG1pbiwgYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzYzMjM4MTk3LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.VfR1KPnZMzqWJrNlDdjwS4PCmFgp4XiEqNBNaNckcJA


GET {{HotelListing.Api_HostAddress}}/api/countries
Authorization: Bearer {{token}}
#X-Api-Key:{{apikey}}

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name":"Lebanon",
  "shortname":"LB"
}

###
@id=577
DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Authorization: Bearer {{token}}


###
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Authorization: Bearer {{token}}

###

PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
"Id": 248,
 "name":"Lebanon",
  "shortName":"LB"
}
###
PATCH {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Authorization: Bearer {{token}}
Content-Type:application/json-patch+json
[ 
  { 
    "op":"replace",
    "path":"/shortName",
    "value":"LB"
  }
]
###
PATCH {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Authorization: Bearer {{token}}
Content-Type:application/json-patch+json
[ 
  { 
    "op":"replace",
    "path":"/countryid",
    "value":10000
  }
]

###

GET {{HotelListing.Api_HostAddress}}/api/hotels
Authorization: Bearer {{token}}



###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json
Authorization: Bearer 


{
  "Id":4,
  "Name":"Waterland Hotel",
  "Address": "Ardeh",
  "Rating": 3,
  "CountryId":53,
  "PerNightRate":10

}

###

DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Authorization: Bearer {{token}}


###

GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}?pageNumber=2
Authorization: Bearer {{token}}


###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmE5MmNiZS0yZjI1LTQ4Y2UtYjliZC1jN2UxZjUxNGRiMjYiLCJlbWFpbCI6Im1pY2hhZWxhZG1pbjExQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJmMGU0MjQxNy0zZDEyLTQzZTctYmNlMi02MjQyM2M1NWFlYTkiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzU3NzkxMTgyLCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.Ohnl3cVt7Jn9-vBSD7a36sUitl6dhCJ5Qb-8QE2GtTM


{
  "Id":19,
  "Name": "Mist",
  "Address": "Ehden",
  "rating":4,
  "CountryId":47
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmE5MmNiZS0yZjI1LTQ4Y2UtYjliZC1jN2UxZjUxNGRiMjYiLCJlbWFpbCI6Im1pY2hhZWxhZG1pbjExQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJmMGU0MjQxNy0zZDEyLTQzZTctYmNlMi02MjQyM2M1NWFlYTkiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzU3NzkxMTgyLCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.Ohnl3cVt7Jn9-vBSD7a36sUitl6dhCJ5Qb-8QE2GtTM


{
  "email":"michael@localhost.com",
  "password":"P@assword1",
  "firstName":"Michael",
  "lastName":"Abou Antoun",
  "Role":"Administrator"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
 "email": "AdminAdmin@localhost.com",
  "password": "P@ssword"
}

###

GET {{HotelListing.Api_HostAddress}}/api/countries/52/hotels?pagenumber=1&search=LEEDS&SortBy=rating
Authorization: Bearer {{token}}


###
