@HotelListing.Api_HostAddress = https://localhost:7238

GET {{HotelListing.Api_HostAddress}}/api/countries

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
  "name":"Lebanon",
  "shortname":"LB"
}

###
@id=47
DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
"Id": 47,
 "name":"Lebanon",
  "shortName":"lb"
}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Id":4,
  "Name":"Mist hotel",
  "Address": "Ehden",
  "Rating": 3,
  "CountryId":47

}

###

DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "Id":19,
  "Name": "Mist",
  "Address": "Ehden",
  "rating":4,
  "CountryId":47
}

###
