@HotelListing.Api_HostAddress = https://localhost:7238
@apikey=ac123
@json=application/json
GET {{HotelListing.Api_HostAddress}}/api/countries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOTM1MzQ3My00YWYyLTQxZDMtYmU2ZS1lM2RhMTc1NDBmZDIiLCJlbWFpbCI6Im1pY2hhZWxhYm91YW50b3VuQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJiNTE0YmRjZS1jYzJhLTQ1NzEtYTg1NC0yOGM4MjdjNDM3OTYiLCJuYW1lIjoiQWJvdSBBbnRvdW4sIE1pY2hhZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzU4NjIwNzAyLCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.eWqGrGeVss1mKG39NZ0CIeZQisUjrMo1uo3AQgyLo3A
#X-Api-Key:{{apikey}}

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMzAxMTBmMC03N2M1LTQ3MzUtODI1OS01NzAxMDEwY2M5NGQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiIzNzkzMjFmZi1iYWExLTRkOGQtOTFjNi02OTEwOWRkNzY2OTUiLCJuYW1lIjoiYWRtaW4sIGFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc1ODk3Mzk0NSwiaXNzIjoiSG90ZWxMaXN0aW5nQVBJIiwiYXVkIjoiSG90ZWxMaXN0aW5nQVBJQ2xpZW50In0.rBCvZDlWVvjpSg_tXxexJHTaqkzyXnrGP9vfZO5XL5E

{
  "name":"Lebanon",
  "shortname":"LB"
}

###
@id=20
DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MjE4YWU0OC00MDA5LTQ3MmMtYTViNy1kMDRjNGIyYWQzNmQiLCJlbWFpbCI6ImNoYXJiZWxAbG9jYWxob3N0LmNvbSIsImp0aSI6IjEwYTQwNTc4LTA5OGMtNDczZi1hMDg5LTdjYmRhNGE0MzZmZSIsIm5hbWUiOiJBYm91IEFudG91biwgQ2hhcmJlbCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NTg2NDg3NDcsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.kC4AuxMVg1NuaY7SOD8TK6IRcR5GfLOm9rAHmEE7jpY


###
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZGY3ZTc3ZS1iMjI3LTRkNmQtYTA0ZC04ZGQwYTAyODJmN2YiLCJlbWFpbCI6Im1pY2hhZWxAbG9jYWxob3N0LmNvbSIsImp0aSI6ImVkOTAxZjNlLWZjYmItNDgwYy04ZWIzLTAzZmU5ODc4MTlkYyIsIm5hbWUiOiJMYXN0LCBGaXJzdCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NTc3OTAwMzYsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.0NcEpFeQKDcJC7wt8rqMm0qSaYVtOiGE76_R7fADkhw

###

PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMzAxMTBmMC03N2M1LTQ3MzUtODI1OS01NzAxMDEwY2M5NGQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiIzNzkzMjFmZi1iYWExLTRkOGQtOTFjNi02OTEwOWRkNzY2OTUiLCJuYW1lIjoiYWRtaW4sIGFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc1ODk3Mzk0NSwiaXNzIjoiSG90ZWxMaXN0aW5nQVBJIiwiYXVkIjoiSG90ZWxMaXN0aW5nQVBJQ2xpZW50In0.rBCvZDlWVvjpSg_tXxexJHTaqkzyXnrGP9vfZO5XL5E

{
"Id": 47,
 "name":"Lebanon",
  "shortName":"lb"
}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZGY3ZTc3ZS1iMjI3LTRkNmQtYTA0ZC04ZGQwYTAyODJmN2YiLCJlbWFpbCI6Im1pY2hhZWxAbG9jYWxob3N0LmNvbSIsImp0aSI6ImVkOTAxZjNlLWZjYmItNDgwYy04ZWIzLTAzZmU5ODc4MTlkYyIsIm5hbWUiOiJMYXN0LCBGaXJzdCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NTc3OTAwMzYsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.0NcEpFeQKDcJC7wt8rqMm0qSaYVtOiGE76_R7fADkhw



###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMzAxMTBmMC03N2M1LTQ3MzUtODI1OS01NzAxMDEwY2M5NGQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiIzNzkzMjFmZi1iYWExLTRkOGQtOTFjNi02OTEwOWRkNzY2OTUiLCJuYW1lIjoiYWRtaW4sIGFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTc1ODk3Mzk0NSwiaXNzIjoiSG90ZWxMaXN0aW5nQVBJIiwiYXVkIjoiSG90ZWxMaXN0aW5nQVBJQ2xpZW50In0.rBCvZDlWVvjpSg_tXxexJHTaqkzyXnrGP9vfZO5XL5E


{
  "Id":4,
  "Name":"Waterland Hotel",
  "Address": "Ardeh",
  "Rating": 3,
  "CountryId":53,
  "PerNightRate":10

}

###

DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZGY3ZTc3ZS1iMjI3LTRkNmQtYTA0ZC04ZGQwYTAyODJmN2YiLCJlbWFpbCI6Im1pY2hhZWxAbG9jYWxob3N0LmNvbSIsImp0aSI6ImVkOTAxZjNlLWZjYmItNDgwYy04ZWIzLTAzZmU5ODc4MTlkYyIsIm5hbWUiOiJMYXN0LCBGaXJzdCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NTc3OTAwMzYsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.0NcEpFeQKDcJC7wt8rqMm0qSaYVtOiGE76_R7fADkhw


###

GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOTM1MzQ3My00YWYyLTQxZDMtYmU2ZS1lM2RhMTc1NDBmZDIiLCJlbWFpbCI6Im1pY2hhZWxhYm91YW50b3VuQGxvY2FsaG9zdC5jb20iLCJqdGkiOiI5MWFmZThlNi0zMWJjLTRlZGEtODJiNC0yYzVjZDZkYzRlNDQiLCJuYW1lIjoiQWJvdSBBbnRvdW4sIE1pY2hhZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzU4NjE3NTIyLCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.r7RQsMQVqnXR8-DLX3T9z8arUcTtSZFqeUrzoFbnzbw


###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmE5MmNiZS0yZjI1LTQ4Y2UtYjliZC1jN2UxZjUxNGRiMjYiLCJlbWFpbCI6Im1pY2hhZWxhZG1pbjExQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJmMGU0MjQxNy0zZDEyLTQzZTctYmNlMi02MjQyM2M1NWFlYTkiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzU3NzkxMTgyLCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.Ohnl3cVt7Jn9-vBSD7a36sUitl6dhCJ5Qb-8QE2GtTM


{
  "Id":19,
  "Name": "Mist",
  "Address": "Ehden",
  "rating":4,
  "CountryId":47
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmE5MmNiZS0yZjI1LTQ4Y2UtYjliZC1jN2UxZjUxNGRiMjYiLCJlbWFpbCI6Im1pY2hhZWxhZG1pbjExQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJmMGU0MjQxNy0zZDEyLTQzZTctYmNlMi02MjQyM2M1NWFlYTkiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzU3NzkxMTgyLCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.Ohnl3cVt7Jn9-vBSD7a36sUitl6dhCJ5Qb-8QE2GtTM


{
  "email":"michael@localhost.com",
  "password":"P@assword1",
  "firstName":"Michael",
  "lastName":"Abou Antoun",
  "Role":"Administrator"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email":"charbel@localhost.com",
  "password":"P@assword1"
}

###
